### ISSUE TITLE
SyntaxError: invalid syntax al ejecutar con la ultima versión de python 

### ISSUE THREAD

**Issue by robotiko** [Domatix/facturaplus#1]
Windows 10 Pro
instalación nueva de Python y dependencias, al ejecutarse  lanza error de sintaxis:

C:\>python import_product.py
Traceback (most recent call last):
  File "import_product.py", line 2, in <module>
    import ydbf
  File "C:\Users\I\AppData\Local\Programs\Python\Python37\lib\site-packages\ydbf\__init__.py", line 96, in <module>
    from ydbf.reader import YDbfReader
  File "C:\Users\l\AppData\Local\Programs\Python\Python37\lib\site-packages\ydbf\reader.py", line 255
    except UnicodeDecodeError, err:
                             ^
SyntaxError: invalid syntax

**Comment by NachoSerra** [comment]
A nosotros no nos ha fallado, si detectas algún bug puedes corregirlo haciéndome un PR.
En todas las pruebas que hemos hecho no nos ha fallado.
