### ISSUE TITLE
Fallo al importar facturas

### ISSUE THREAD

**Issue by jagarciavi** [Domatix/facturaplus#3]
Buenas, he ejecutado el script para importar productos correctamente, pero al importar facturas, obtengo el siguiente error usando Python 2.7:

`Traceback (most recent call last):
  File "import_factura.py", line 131, in <module>
    importar()
  File "import_factura.py", line 97, in importar
    partner = partner_obj.create(partner)
  File "/usr/local/lib/python2.7/dist-packages/erppeek.py", line 1237, in create
    values = self._unbrowse_values(values)
  File "/usr/local/lib/python2.7/dist-packages/erppeek.py", line 1271, in _unbrowse_values
    field_type = self._fields[key]['type']
KeyError: 'opt_out'`

**Comment by NachoSerra** [comment]
Depende de la versión de Odoo que estés utilzando el campo opt_out de los clientes puede haber cambiado de nombre

**Comment by pepereiscat** [comment]
Hola!

He conseguido que me funcionen todos os scripts con Odoo15, si queréis puedo compartirlos, pero el último script no me funciona, el import_factura_linea.py.

He modificado los campos que creo que son y tal, pero me aparece lo siguiente...

Traceback (most recent call last):
  File "import_factura_linea.py", line 74, in <module>
    importar()
  File "import_factura_linea.py", line 69, in importar
    invoice_line_id = invoice_line_obj.create(invoice_vals)
  File "C:\Python27\lib\site-packages\erppeek.py", line 1238, in create
    new_id = self._execute('create', values, context=context)
  File "C:\Python27\lib\site-packages\erppeek.py", line 826, in execute
    res = self._execute(obj, method, *params)
  File "C:\Python27\lib\site-packages\erppeek.py", line 462, in <lambda>
    wrapper = lambda s, *args: s._dispatch(name, args)
  File "C:\Python27\lib\xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "C:\Python27\lib\xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "C:\Python27\lib\xmlrpclib.py", line 1316, in single_request
    return self.parse_response(response)
  File "C:\Python27\lib\xmlrpclib.py", line 1493, in parse_response
    return u.close()
  File "C:\Python27\lib\xmlrpclib.py", line 800, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault warning -- UserError

The operation cannot be completed: another model requires the record being deleted. If possible, archive it instead.

Model: Journal Item (account.move.line), Constraint: account_move_line_origin_line_id_fkey: ''>

Me podéis ayudar?

Gracias!

**Comment by nachoserra-domatix** [comment]
Hola @pepereiscat estos scripts se hicieron para Odoo 11, en versiones superiores a 13 las facturas cambiaron bastante a nivel técnico(borraron el modelo account.invoice y usaron el de asientos 'account.move' y 'account.move.line' por lo que es normal que no funcionen ya que no están preparados para esa versión de Odoo.

Sería necesario modificar los valores del modelo, yo no tengo previsto actualizarlo ahora mismo pero si alguien se anima a hacer un PR para la v15, con gusto lo reviso y lo añado al repositorio.

Saludos!

**Comment by nachoserra-domatix** [comment]
Este fallo en concreto es posible que te esté diciendo que el campo origin_line_id no esté correctamente informado en account.move.line.

Este campo por lo que veo viene de un módulo de oca llamado account_invoice_refund_link. que lo que hace es añadir un enlace desde una factura rectificativa a la factura desde la que se ha hecho. Si lo que se importa es una rectificativa, si tienes este módulo tienes que especificarle cual es el origen o borrar ese módulo e instalarlo a posterior
